### PR TITLE
Overwrite CSS for the WhyDonate plugin

### PR DESCRIPTION
**Pull request by franei**
This defines the `whydonate` class for overwriting some of the default styling of the WhyDonate donation button, progress bar, and donation form. See [this Trello card](https://trello.com/c/LouTL1SI/70-add-whydonatenl-plugin-to-website) for the request and some before/after screenshots.

The `wd-center` class can be used for centering the button/progress bar:
```html
<div class="whydonate wd-center">
  [whydonate id="weuzk"]
</div>
```

### CODE REVIEW

**Comment by SamLubbers** [comment]
@franei I just need to check with Marieke as she wanted to make all main CTA buttons black.

**Review by SamLubbers — CHANGES_REQUESTED** [review]
@franei I checked with Marieke and she said that to keep the design consistent we will make all buttons black, except buttons which are on top of a dark overlay. Those buttons will be blue 👌

**Comment by franei** [comment]
I've changed it the background colour. It looks like this now:
image
image

**Review by SamLubbers — APPROVED** [review]
Wow what a quick change 😁 Now it's all good to go 🚀

**Pull request merged**
